### PR TITLE
DOM

### PR DESCRIPTION
**Pull request by hisbvdis**
### DOM

[Demo](https://hisbvdis.github.io/kottans-frontend/pages/dom/) |
[Code base](https://github.com/hisbvdis/kottans-frontend/tree/main/pages/dom)

The code is submitted in a dedicated feature branch.

Only code files are submitted.

Please, review.

### CODE REVIEW

**Comment by hisbvdis** [comment]
@madmaxWMFU , надеюсь, теперь всё правильно

**Comment by madmaxWMFU** [comment]
Your pull request consists of two task popup and dom. 
Maybe you created a branch in your popup branch. 
It was necessary to create it in the main branch.

**Comment by madmaxWMFU** [comment]
@OleksiyRudenko, Can you help with this? Maybe I'm wrong.

**Comment by hisbvdis** [comment]
@madmaxWMFU ,
Видимо, случайно зацепил файлы из ветки задачи с попапом.
Удалил.

У задачи с попапом отдельная ветка и PR уже объединён: https://github.com/kottans/frontend-2022-homeworks/pull/247

**Review by madmaxWMFU — APPROVED** [review]

**Pull request merged**
