### PR TITLE
Add OOP to tiny-js-world

### PR DESCRIPTION
**Pull request by HelenGreent**
### OOP exercise

[Demo](https://helengreent.github.io/a-tiny-JS-world) |
[Code base](https://github.com/HelenGreent/a-tiny-JS-world/blob/oop-exercise/index.js)

The code is submitted in a dedicated feature branch.

Only code files are submitted.

Please, review.

### CODE REVIEW

**Comment by HelenGreent** [comment]
re-open

**Comment by HelenGreent** [comment]
re-open

**Comment by OleksiyRudenko** [comment]
@HelenGreent any reaction on bots' asks?

**Comment by HelenGreent** [comment]
self-check done

**Review by OleksiyRudenko — APPROVED** [review]
@HelenGreent well done

**Pull request merged**
