### PR TITLE
Add Friend App

### PR DESCRIPTION
**Pull request by D1telo**
# Friend App
[Demo](https://d1telo.github.io/Friends_App/) |
[Code base](https://github.com/D1telo/Friends_App/)

The code is submitted in a dedicated feature branch.

Only code files are submitted.

Please, review.

### CODE REVIEW

**Comment by OleksiyRudenko** [comment]
This won't work
image

**Comment by OleksiyRudenko** [comment]
Also submission for [Building a Tiny JS World](https://github.com/kottans/frontend/blob/master/tasks/js-pre-oop.md) is missing

**Comment by OleksiyRudenko** [comment]
What #723 has to do with this PR?

**Comment by D1telo** [comment]
> Also submission for [Building a Tiny JS World](https://github.com/kottans/frontend/blob/master/tasks/js-pre-oop.md) is missing

Sorry I just thought that was [enough](https://github.com/OleksiyRudenko/a-tiny-JS-world/pull/197 ). I created a [new pr](https://github.com/kottans/frontend-2022-homeworks/pull/739)

**Comment by D1telo** [comment]
> What #723 has to do with this PR?

this just T9 ,sry i`m fixed it ,and add full files with friends app

**Comment by OleksiyRudenko** [comment]
You added files needed for review. But there is still a submodule that is not required and will also pollute a shared repository.
Please remove.

**Pull request closed without merging**
