### PR TITLE
Building a Tiny JS World

### PR DESCRIPTION
**Pull request by Dovahkiin1991**
### Building a Tiny JS World

[Demo](https://dovahkiin1991.github.io/a-tiny-JS-world/) |
[Code base](https://github.com/Dovahkiin1991/a-tiny-JS-world)

The code is submitted in a dedicated feature branch.

Only code files are submitted.

Please, review.

### CODE REVIEW

**Comment by Dovahkiin1991** [comment]
Hey, I made self-checks and all looks ok.

**Review by OleksiyRudenko — CHANGES_REQUESTED** [review]
@Dovahkiin1991 
Please copy all requirements re variable naming from all the materials linked by the bot and paste them as a comment, and fix code accordingly.

**Comment by Dovahkiin1991** [comment]
- Variable name should be camelCase.
- Variable names should not be too short or too obscure
- Variable names should not be too general.
- Functions denote actions hence their names should start with a verb. Variables containing strings, numbers, objects are normally nouns. Boolean variables/functions start with is, does, has etc. A variable containing multiple entities and functions returning lists contain entity name in plural form.

@OleksiyRudenko Made changes, according to this list.

**Review by OleksiyRudenko — APPROVED** [review]
@Dovahkiin1991 well done!

FYI, `key` is a term in programming domain. In real life living creatures are characterized by properties or features. One says "Purring is distinctive **feature (or property)** of felines" rather than "Purring is the distinctive **key** of felines".

So `key` is a generic term in the context of given business domain.

**Pull request merged**
