### PR TITLE
Tini Js World

### PR DESCRIPTION
**Pull request by martthaa**
### Tini JS World

[Demo](https://martthaa.github.io/a-tiny-JS-world/) |
[Code base](https://github.com/martthaa/a-tiny-JS-world)

The code is submitted in a dedicated feature branch.

Only code files are submitted.

Please, review.

### CODE REVIEW

**Comment by OleksiyRudenko** [comment]
Deleting code of past tasks may lead to... their deletion from the repo.
It is recommended that you revisit contribution instructions and follow them. It is important to create a branch for the new task when on `main`. There is a good reason for that

**Comment by martthaa** [comment]
when I add a new task, I create a new branch (I don't write anything on the main page)
git checkout -b <name of branch> 
...make changes....
git add  .
git commit -m " "
git push --set-upstream origin <branch name>
please tell me what i can do wrong

**Comment by OleksiyRudenko** [comment]
> when I add a new task, I create a new branch (I don't write anything on the main page)
> git checkout -b
> ...make changes....
> git add .
> git commit -m " "
> git push --set-upstream origin
> please tell me what i can do wrong

You may have committed directly to your fork's `main` at some point or mixed the order of branches when merging.

Looks like this is where it happened.
image

You need to re-sync your fork's `main` with original homerworks repo `main`. Check [this](https://github.com/kottans/frontend-2022-homeworks/blob/main/README.md#%D0%B4%D0%BE%D0%B2%D1%96%D0%B4%D0%BA%D0%BE%D0%B2%D1%96-%D0%BC%D0%B0%D1%82%D0%B5%D1%80%D1%96%D0%B0%D0%BB%D0%B8-%D1%82%D0%B0-%D1%83%D1%81%D1%83%D0%BD%D0%B5%D0%BD%D0%BD%D1%8F-%D0%BF%D1%80%D0%BE%D0%B1%D0%BB%D0%B5%D0%BC) for resolution guidelines (Довідкові матеріали та усунення проблем)

**Review by OleksiyRudenko — CHANGES_REQUESTED** [review]
@martthaa good job!
Please double check your code against the bot's message.
At least one requirement is not met.

P.S. Also make sure you fix your fork. The PR looks polluted with unrelated commits.

**Review by OleksiyRudenko — APPROVED** [review]
@martthaa well done!

**Pull request merged**
