### PR TITLE
added hooli-popup task

### PR DESCRIPTION
**Pull request by VladimirRutskiy**
### HTML і CSS практика: Hooli-style Popup

[Demo](https://vladimirrutskiy.github.io/hooli-popup/) |
[Code base](https://github.com/VladimirRutskiy/hooli-popup)

The code is submitted in a dedicated feature branch.

Only code files are submitted.

Please, review.

### CODE REVIEW

**Comment by VladimirRutskiy** [comment]
I checked my homework. it is following to recommendation.

**Comment by artem-trubin** [comment]
Hey! Demo looks amazing, but there are issues with files. Your` Files changed` tab show that you are adding a submodule, not just plain files. It means that the folder you're trying to add is a git repository. You should not include git repositories inside other git repositories. Please fix it.

**Review by artem-trubin — CHANGES_REQUESTED** [review]
Hey! Demo looks amazing, but there are issues with files. Your` Files changed` tab show that you are adding a submodule, not just plain files. It means that the folder you're trying to add is a git repository. You should not include git repositories inside other git repositories. Please fix it.

**Comment by artem-trubin** [comment]
Also, part of the task was to hide the `More` button when it gets clicked.

**Review by artem-trubin — CHANGES_REQUESTED** [review]
Hey, great work, I love the design! Let's improve it a little:
- please add empty lines at the end of each file. You can set your editor to do this for you automatically on save. [Reason](https://stackoverflow.com/questions/2287967/why-is-it-recommended-to-have-empty-line-in-the-end-of-a-source-file#:~:text=The%20empty%20line%20in%20the,can%20handle%20the%20EOF%20marker.)
- There are some redundant comments in your code. CSS seems nice but in HTML, things like `FAVICON` and there's only one line of code underneath it and its favicon seems a little strange. Like why would you comment about `header` if it's literally the name of the tag?

**Comment by VladimirRutskiy** [comment]
Thank you for review) I have fixed all remarks.

**Pull request merged**
