### PR TITLE
HTML&CSS Practise PopUp

### PR DESCRIPTION
**Pull request by martthaa**
### HTML&CSS Practise

[Demo](https://martthaa.github.io/sweetPopUp/) |
[Code base](https://github.com/martthaa/sweetPopUp)

The code is submitted in a dedicated feature branch.

Only code files are submitted.

### CODE REVIEW

**Comment by OleksiyRudenko** [comment]
Is it a duplicate of #162 ?

**Comment by martthaa** [comment]
Yes

**Comment by OleksiyRudenko** [comment]
Why do we need this PR?

**Comment by martthaa** [comment]
I had problems with adding files, I have pushed to github folder, but then I  see a white arrow on my folders and when i click on the folder, it does not open it. On my local machine, it has contents, but in github i cannot access them. Well, I tried different commands that I found on the Internet about this, but the problem was not fixed and I decided to add files through the interface, but the mentor asked me to solve the problem with the file, I did not succeed, so I decided to add a new branch, where I created a new PR.

 Now I understand why I got this file, my mistake was that I just past the folder (which I previously pushed into GitHub to create Demo), that is not correct, because in fact I wanted to create a repository inside a repository. Thus was created gitlink - nested Git repository

**Comment by OleksiyRudenko** [comment]
Can we close this PR or do we still need it?

**Comment by martthaa** [comment]
I think to close

**Comment by martthaa** [comment]
sorry, that I distracted you with this PR

**Comment by OleksiyRudenko** [comment]
Closing this as the task is already in review under #162

**Comment by OleksiyRudenko** [comment]
@martthaa no worries. We figured this out

**Pull request closed without merging**
