### PR TITLE
Task "A tiny js world" completed

### PR DESCRIPTION
**Pull request by Mifaresss**
### A tiny js world

[My tiny js world](https://mifaresss.github.io/a-tiny-JS-world/) | [Code base](https://github.com/Mifaresss/a-tiny-JS-world/tree/populate-world)

The code is submitted in a dedicated feature branch. Only code files are submitted.
Please, review.

### CODE REVIEW

**Comment by Mifaresss** [comment]
This check was carried out before PR

**Comment by OleksiyRudenko** [comment]
> This check was carried out before PR

Missed requirements:

(1)
https://github.com/OleksiyRudenko/a-tiny-JS-world#the-job

(2)
> - [ ] Code is [DRY](https://en.wikipedia.org/wiki/Don%27t_repeat_yourself), which means that whenever you see a pattern in your code those should be eliminated as much as possible. Examples:
>    - `print(dog); print(cat); etc ... ` should be refactored employing `Array.forEach` as the least
>    - `` `${obj.legs}; ${obj.name}; etc...` `` (yes, strings are also code) must be refactored employing appropriate `Array` methods

(3)
> Object methods like keys, values, entries shouldn't be used when a particular order is required as these do not guarantee any particular order of keys/values. Same refers to for...of and for...in when applied to objects.
Hint: List explicitly the properties used to form an object presentation string.

**Comment by Mifaresss** [comment]
Worked on the bugs, please review

**Comment by OleksiyRudenko** [comment]
> > This check was carried out before PR
> 
> Missed requirements:
> 
> (1) https://github.com/OleksiyRudenko/a-tiny-JS-world#the-job

Is still incomplete.

Also at least one of universal recommendations from bot checklist is still missed.

Please do not expect mentors to red-pen your work. Imagine you are on a commercial project and paid for the work you do.

**Comment by Mifaresss** [comment]
Oh, sorry. Can you be more specific about what I'm missing [here](https://github.com/OleksiyRudenko/a-tiny-JS-world#the-job)?

Variable name in function corrected

**Comment by OleksiyRudenko** [comment]
Item 1 of the job. Properties that inhabitants have.

**Comment by Mifaresss** [comment]
Are these properties required? I did not add them because I thought they were not required: https://skr.sh/sFpX3F9Jwxs

**Comment by OleksiyRudenko** [comment]
Naturally, dogs do not have hands. But I will make this requirement more specific, so it reads without the requirements in their whole in this section

**Comment by Mifaresss** [comment]
Ready) Added properties: legs and arms

**Comment by OleksiyRudenko** [comment]
image

**Comment by Mifaresss** [comment]
Sory, I don't understand(

**Comment by Mifaresss** [comment]
Are you saying that I didn't replace the data in the main repo? If yes, then it's already fixed.

**Comment by Mifaresss** [comment]
I seem to understand. Where did a copy of the submissions folder come from, only in Russian. This is most likely somehow connected with Google translator, which automatically translates the page for me. But I still can't figure out how he created a duplicate of the folder..

**Comment by Mifaresss** [comment]
Look please. Is everything okay now?

**Review by OleksiyRudenko — APPROVED** [review]
@Mifaresss well done!

P.S. Avoid "fixing" some else's "mistakes". We do not want to intefere with code not related to our task, not in the same PR anyway.
It is a coincidence that the removed files do not already exist in upstream. Otherwise this files removal would block this PR as we'd need some extra time to resolve the issue.


image

**Pull request merged**
