### PR TITLE
Sidemenu

### PR DESCRIPTION
**Pull request by martthaa**
###   DOM task

[Demo](https://martthaa.github.io/Music-SideBar-Menu/) |
[Code base](https://github.com/martthaa/Music-SideBar-Menu)

The code is submitted in a dedicated feature branch.

Only code files are submitted.

Please, review.

### CODE REVIEW

**Comment by OleksiyRudenko** [comment]
This PR contains two applications? Is this intended?

**Comment by martthaa** [comment]
Hi, @OleksiyRudenko, I edited PR. Please check if everything is ok

**Comment by OleksiyRudenko** [comment]
This PR still contains files from a different task. Please fix this.
image

**Comment by martthaa** [comment]
Done :)

**Comment by OleksiyRudenko** [comment]
This PR is fixed for now by deletion of unrelated files.
Deletion may have unexpected side effects. Like this PR will suddenly suggest to delete PopUp task files once the PopUp PR is merged. So, watch it.
Consider sticking to submission instructions - it is important to add code to the project properly.

**Comment by martthaa** [comment]
thanks for the corrections and advice! I appreciate. Now I have to wait for code review?

**Comment by OleksiyRudenko** [comment]
> Now I have to wait for code review?

Read the bot's comment above carefully and follow what it suggests.

**Comment by martthaa** [comment]
I completed self-checks

**Review by A-Ostrovnyy — CHANGES_REQUESTED** [review]
Awesome design!
One of the main ideas of this task is markup only for displaying selected data not for storing it. In your case, you store all data in markup. You must display only selected data. All the rest data must be in another place. Create an array with objects of data in your js file and just display only the selected object of data.

**Pull request closed without merging**
