### PR TITLE
Tw2

### PR DESCRIPTION
**Pull request by vovan-zt**
### OOP exercise

[Demo](https://vovan-zt.github.io/a-tiny-JS-world/) |
[Code base](https://github.com/vovan-zt/a-tiny-JS-world)

The code is submitted in a dedicated feature branch.

Only code files are submitted.

Please, review. repeated requested

### CODE REVIEW

**Comment by OleksiyRudenko** [comment]
Good PR, just like a good function or a good commit, does only one job. E.g. adds a new feature OR fixes mistakes.
There was a reason why last correction we did actually worked.
Take a learning from that case and project it on your future experiences. Be thoughtful.
image
.

**Comment by vovan-zt** [comment]
B2. Коли потрібні будь-які зміни
Щоразу, коли ви хочете або вам буде запропоновано внести будь-які зміни, виконайте такі дії:

B21. Оновіть свою програму (у відповідному app repo):

впровадити зміни
переконайтеся, що публікація вашої програми оновлена
B22. Оновіть свій PR - у вашому homeworks local repo:

git checkout <task-branch-name>
скопіюйте змінені файли (один за одним) у ваш каталог завдань із app repo
stage, commit і push
Ваш PR буде оновлено автоматично.

B23. Перевірте свій PR і повідомте ментора:

перейдіть до свого PR у homeworks main repo
перевірте надіслані файли в розділі Файли змінено; ви повинні побачити свої останні зміни у файлах
клацніть Re-request review у списку ваших PR-рев'юерів щоб привернути увагу наставників, щоб вони знали, що є нові зміни для перегляду
Коли ваш PR буде нарешті змержено, напишіть міркування про завдання і досвід код рев'ю до вашого щоденника студента (ваш repo kottans-frontend):

що для вас було нового
що вас здивувало
що ви збираєтеся використовувати в майбутньому


I already figured it out for myself.
I will do the same in other projects.

Before each created project, I ran the command.

**git checkout main
git pull upstream main
git push origin main**

Was it my fault?

**Comment by OleksiyRudenko** [comment]
If it was a commercial project this PR would be probably denied altogether.
It adds a required feature. It also introduces changes to unrelated parts of the project.
Encapsulation and cleanliness of PRs and commits is no less important that encapsulation and cleanliness of code.
Please make this PR contain only what is required by the task and contribution guidelines.

**Comment by OleksiyRudenko** [comment]
@vovan-zt 

Brief analysis:
image

This means that your fork's `main` contains commits that are not on the upstream repo's `main`.

This happens when something is committed to the fork's main branch directly rather than via `branch-commit-push-PR-merge` workflow or when merging of feature branch with main was done with wrong branches order (`checkout feature-branch && merge main` is not the same as `checkout main && merge feature-branch`). Fork's main branch should be updated from `upstream`'s main branch only.

These "foreign" commits make main branch histories diverge and that's why extra merge commits required/appear on the fork's branch, making history diverge even further with every `git pull upstream`.

Follow `... commits ahead` link to see the difference between fork and upstream
image

This history difference will cause more troubles.

There are two options as to how to resolve the issue:
1. Re-sync fork's and upstream's main branches (guidelines are available under item 2 in [Contributions Troubleshooting section](https://github.com/kottans/frontend-2022-homeworks#%D0%B4%D0%BE%D0%B2%D1%96%D0%B4%D0%BA%D0%BE%D0%B2%D1%96-%D0%BC%D0%B0%D1%82%D0%B5%D1%80%D1%96%D0%B0%D0%BB%D0%B8-%D1%82%D0%B0-%D1%83%D1%81%D1%83%D0%BD%D0%B5%D0%BD%D0%BD%D1%8F-%D0%BF%D1%80%D0%BE%D0%B1%D0%BB%D0%B5%D0%BC)). Not an easy approach but you will learn something new, gain a new skill and hopefully will understand git better.
2. Kill the fork and local repo, re-fork again. But any currently **open PRs will get automatically closed** as the fork won't exist anymore. **You will need to re-submit code** and catch up to the ongoing reviews **somehow**.

Let me know if you want to follow option 1. It is doable and less disruptive. We can complete it making baby steps.

The 2nd option seems simpler but will require no less efforts altogether.

**Comment by OleksiyRudenko** [comment]
Added label to find the PR faster using PR filters.

**Comment by vovan-zt** [comment]
I can always crush my fork. First you need to try option number 1

**Comment by OleksiyRudenko** [comment]
That's a proper attitude.

When you read the materials, please share your findings on your repo and suggest an action plan. We shall review it, adjust if needed and implement.

**Comment by vovan-zt** [comment]
git branch backup-feature 
git checkout master
git branch backup-master 

git checkout 676172e
git branch -f master 
git checkout master
git push -f 

git remote add upstream https://github.com/kottans/frontend-2022-homeworks.git
git pull upstream master
git push origin main


git branch -f feature-branch
git checkout feature-branch
make some changes
git cherry-pick 676172e
git push -f


git branch -d backup-feature 
git push origin --delete backup-feature 

git branch -d backup-master 
git push origin --delete backup-master

**Comment by OleksiyRudenko** [comment]
General, this repo's main branch is `main` not `master`

**Block 2:**
```
git checkout https://github.com/kottans/frontend-2022-homeworks/commit/676172ed7f1f177ac439b04b2c4c4acdb07184f6
git branch -f master
git checkout master
git push -f
```
Does 676172e belong to upstream's master?
If not then we will still have a problem, just smaller. We need to have main branch pointer on fork point at the latest commit on upstream's main branch that exists both on upstream and fork.


**Block 3:**
```
git remote add upstream https://github.com/kottans/frontend-2022-homeworks.git
```
We should have this already set up. Although no harm in re-assigning upstream once again.

**Block 4:**
```
git branch -f feature-branch
git checkout feature-branch
make some changes
git cherry-pick https://github.com/kottans/frontend-2022-homeworks/commit/676172ed7f1f177ac439b04b2c4c4acdb07184f6
git push -f
```
Is this exactly the commit you want to keep? Why?
If there is a good reason, we still need to "save" other commits on this PR.

Also replace `feature-branch` with actual branch name you want to have.

**Comment by vovan-zt** [comment]
I accidentally deleted 4 commits ahead via github

**Comment by vovan-zt** [comment]
Will this somehow help my problem or am I making it worse?

**Comment by vovan-zt** [comment]
Maybe it makes sense to delete this branch and create a new one? 
Since I'm already a little confused

**Comment by OleksiyRudenko** [comment]
Probably, it will be easier to re-do this PR from the scratch

**Pull request closed without merging**
