### PR TITLE
wrong merging path

### PR DESCRIPTION
**Pull request by vovan-zt**
### popup

[Demo](https://vovan-zt.github.io/popup2022/) |
[Code base](https://github.com/vovan-zt/popup2022.git)

The code is submitted in a dedicated feature branch.

wrong merging path

### CODE REVIEW

**Comment by artem-trubin** [comment]
Don't just add new files, remove old ones.

**Comment by artem-trubin** [comment]
For passing-by mentors, this PR is for moving files that are already merged, just with a wrong path.

**Comment by OleksiyRudenko** [comment]
@vovan-zt normally renaming with `git mv` does the job

**Comment by vovan-zt** [comment]
then I need to do it on the first branch that was confirmed and delete this branch?

**Comment by OleksiyRudenko** [comment]
You must have the wrong-named files on your `main` where you branched off to create this PR.
If it is true then just delete those, commit and update this PR.
If it is not true then you'd need to update your `main`, rebase this branch on top of it and make the situation true ;)
This way we emulate files renaming with `git mv`.

**Comment by OleksiyRudenko** [comment]
Now it looks all good.
image

Other changes are minor (formatting), although a few empty lines look redundant. But I guess we can live with it.

@artem-trubin WDYT?

**Pull request merged**
