### PR TITLE
OOP (re-uploaded)

### PR DESCRIPTION
**Pull request by kovalov**
### OOP

[Demo](https://kovalov.github.io/a-tiny-JS-world/) |
[Code base](https://github.com/kovalov/a-tiny-JS-world)

The code is submitted in a dedicated feature branch.

Only code files are submitted.

Please, review.

### CODE REVIEW

**Comment by kovalov** [comment]
Re-uploaded due to commits issues.
PR took commits from outer users/branches.

**Comment by OleksiyRudenko** [comment]
THis PR replaces #32

**Comment by OleksiyRudenko** [comment]
@kovalov please mark items on [**Minimal requirements** list](https://github.com/kottans/frontend-2022-homeworks/pull/46#issuecomment-1202186152) you genuinely believe are properly addressed by the code.

**Optional level-up** and **Bonus** lists are optional.

**Comment by kovalov** [comment]
Current status:
> * [x]  Implement a base class to inherit from
> * [x]  Employ default parameters
> * [x]  Each species is represented with its own class
> * [x]  No need to specify species at instantiation
> * [x]  Classes for species that do not have hands by natural design, do not consequently have `hands` or any equivalent property and do not inherit such properties from any base classes
> * [x]  All inhabitants are stored in a container (array or object)
> * [x]  JS native features are intensively employed (`const`, `let`, `Array.map|join|forEach|...`, etc)
> * [x]  `Object` methods like `keys`, `values`, `entries` as well as `for...in` shouldn't be used as these do not guarantee any particular order of keys/values
> * [x]  Properties used to form an object presentation string must be explicitly listed/specified; Use `Array.map` and `Array.join` to build a presentation string from the list.
> * [x]  `toString` magic method; when implemented `print(inhabitant)` does the job as `.toString` is called implicitly
> * [ ]  A parent class shouldn't know anything about its children's props. Child classes must have good reasons to assign or refer to any parent's props. There are no such reasons in this task. Method overloading is to the rescue when building an inhabitant's presentation string.
> * [ ]  [OOP, SOLID and DRY](https://github.com/OleksiyRudenko/a-tiny-JS-world/blob/master/README.md#learn-on-your-own) principles are intensively employed

**Comment by OleksiyRudenko** [comment]
Seems like there is mismatch between submitted code and demo.

image

... or "Classes for species that do not have hands by natural design, do not consequently have hands or any equivalent property and do not inherit such properties from any base classes" is not fulfilled.

**Comment by kovalov** [comment]
> Seems like there is mismatch between submitted code and demo.
> 
> image
> 
> ... or "Classes for species that do not have hands by natural design, do not consequently have hands or any equivalent property and do not inherit such properties from any base classes" is not fulfilled.

Have updated the code.

**Review by OleksiyRudenko — APPROVED** [review]
Great job!

**Pull request merged**
